trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'Install'
  inputs:
    command: install
- task: Npm@1
  displayName: 'Compile'
  inputs:
    command: custom
    customCommand: run compile
#env:
#    VSCE_PAT: $(VSCE_PAT)