trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- bash: |
    npm install
  displayName: npm install
- bash: |
    npm run compile
  displayName: compile
- bash: |
    npm run package
  displayName: package
