name: Link Checker

on:
  schedule:
    - cron: "0 5 * * *"
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

permissions:
    contents: read
    pull-requests: write
    issues: write

jobs:
    link-checker:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v3.1.0
        
            - name: Link Checker
              id: lychee
              uses: lycheeverse/lychee-action@v1.4.1
              with:
                args: --verbose --no-progress --max-concurrency 2 --exclude-mail --exclude-loopback './**/*.md'
                output: ./lychee/out.md
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Create issue when fail
              uses: peter-evans/create-issue-from-file@v4
              if: (!github.event.pull_request) && ${{ steps.lychee.outputs.exit_code }} != 0
              with:
                title: Link Checker Report
                content-filepath: ./lychee/out.md
                labels: report 📄, automated issue 🤖
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}